version: 1

filters:
  sensitive_info:
    (): __main__.SensitiveFilter

 
formatters:
  livres_f:
    format:  "%(asctime)s - %(module)s - %(funcName)s - %(levelname)s - %(message)s"
    datefmt: "%d/%Y %I:%M"
  transations_f:
    format: "%(name)s - %(levelname)s - %(message)s"
  
handlers:
  livres_h:
    class: logging.StreamHandler
    stream: "ext://sys.stdout"
    formatter: livres_f
  transations_h:
    class: logging.StreamHandler
    stream: "ext://sys.stdout"
    formatter: transations_f

loggers:
  livres:
    level: DEBUG
    handlers: [livres_h]
  transactions:
    level: DEBUG
    handlers: [transations_h]
    filters: [sensitive_info]


