version: 1

formatters:
  simple:
    format:  "%(asctime)s - %(module)s - %(funcName)s - %(levelname)s - %(message)s"
  
handlers:
  console:
    class: logging.StreamHandler
    stream: "ext://sys.stdout"
    formatter: simple

loggers:
  principale:
    level: DEBUG
    handlers: [console]


